key_dict = {'lastprice':'Last Price',
            'shareout':'Share Out',
            'mc':'Market Cap',
            'cash':'Cash',
            'asset':'Total Asset',
            'stdebt':'S.T.Borrowing',
            'ltdebt':'L.T.Borrowing',
            'equity':'Total Equity',
            'revenue': 'Revenue',
            'grossprofit': 'Gross Profit',
            'operatingprofit': 'Operating Profit',
            'netprofit': 'Net.Profit',
            'ebitda': 'EBITDA',
            'interestexpense': 'Interest Expense',
            'dividend': 'Deviden',
            'eps': 'EPS',
            'per': 'PER',
            'bvps': 'BVPS',
            'pbv': 'PBV',
            'roa': 'ROA',
            'roe': 'ROE',
            'der': 'Debt/Equity',
            'des': 'Debt/TotalCap',
            'debit': 'Debt/EBITDA',
            'debitin': 'EBITDA/IntExps'
            }